#!/bin/sh
unset LANG LC_CTYPE LC_ALL LC_COLLATE
make
echo -n "Noun stems: "
grep " ע" wolig.dat | grep -vc "^#"
echo -n "Adjective stems: "
grep " ת" wolig.dat | grep -vc "^#"
echo -n "Verb rules: "
grep " פ" woo.dat | grep -vc "^#"
echo -n "Verb stems: "
grep -c -- "----" out.verbs
echo -n "Shmot Peula derived from verbs: "
wc -l shemp.dat
echo -n Sum of unique nouns and shmot peula:
grep -h " ע" wolig.dat shemp.dat | grep -v "^#"| sed "s/ *#.*$//" | sort -u | wc -l
echo -n "...out of them: needing no inflection hints: "
grep -h " ע" wolig.dat shemp.dat | grep -v "^#"| sed "s/ *#.*$//" | sort -u | grep "ע$" | wc -l
echo -n "                needing explicit gender hints: "
egrep ",(זכר|נקבה)" wolig.dat | grep "ע,"| wc -l
echo -n Extrawords, milot and biza-*:
grep -h "^[א-ת]*" extrawords milot biza-verbs biza-nouns | tr -d - | sort -u | wc -l
# NOTE: to find duplicates in wolig.dat:
# grep " ע" wolig.dat | grep -v "^#"| sed "s/ *#.*$//"|sort |uniq -c | sort -n | less
wc -l milot likelyerrors biza-verbs biza-nouns extrawords
echo
echo -n "Total resulting words: "
(cat out.nouns out.nouns-shemp out.verbs milot extrawords biza-verbs biza-nouns) | grep -h "^[LBא-ת]" | tr -d -| sort -u |wc -l
