document.write ('<SCRIPT LANGUAGE="JavaScript">\n');
document.write ('<!--\n');
document.write ('function mak200_DoFSCommand(command, args) {\n');
document.write ('if ( command=="click" )\n');
document.write ('window.open("http://realmedia.nana.co.il/RealMedia/ads/click_lx.ads/net.nana.co.il/GeneralPage/1459197978/TopLeft/keren-makefet/makefet200.htm/38343434303131643366633331353630");\n');
document.write ('}\n');
document.write ('document.write(');
document.write ("'");
document.write ('<SCRIPT LANGUAGE=VBScript>\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('  on error resume next\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('  Sub mak200_FSCommand(ByVal command, ByVal args)\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('    call mak200_DoFSCommand(command, args)\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('  end sub\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('</SCRIPT>\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('<OBJECT CLASSID="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('  CODEBASE="http://active.macromedia.com/flash4/cabs/swflash.cab#version=4,0,2,0" ID=mak200 WIDTH=200 HEIGHT=200>\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('  <PARAM NAME="movie" VALUE="http://realmedia.nana.co.il/RealMedia/ads/Creatives/keren-makefet/nana_makefet_halvaa200x200.swf">\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('  <PARAM NAME=play VALUE=true>\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('  <PARAM NAME=loop VALUE=true>\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('  <PARAM NAME=menu VALUE=false>\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('  <PARAM NAME=quality VALUE=high>\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('  <PARAM NAME=wmode VALUE=transparent>\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('document.write(');
document.write ("'");
document.write ('</OBJECT>\\');
document.write ('n');
document.write ("'");
document.write (');\n');
document.write ('//-->\n');
document.write ('</SCRIPT>\n');
document.write ('\n');
